project:
  type: book

book:
  title: "Casual Musings on <br> Data Structures and Algorithms"
  author: "Neeldhara Misra"
  margin-header: hyvor.html
  date: "8/2/2022"
  chapters:
    - index.qmd
    - intro.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    html-math-method: katex
  pdf:
    documentclass: scrreprt

resources: 
  - styles.css
  - fonts/